<a href="https://colab.research.google.com/github/Asad3ek/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [6]:
print(pd.__version__)

2.2.3

In [81]:
dataset = {
    'cars' : ['BMW', 'Porsche', 'Nissan', 'Opel', 'Ferrari', 'Hyunday'],
    'counts' : [3, 7, 2, 2, 5, 9],
    'years' : [2024, 2026, 2023, 2020, 2025, 2025],
    'origins' : ['Ger', 'Ger', 'Jap', 'Ger', 'Ita', 'Kor']
}


dataFrame = pd.DataFrame(dataset)
print('dataFrame: ', dataFrame)

dataFrame:        cars  counts  years origins
0      BMW       3   2024     Ger
1  Porsche       7   2026     Ger
2   Nissan       2   2023     Jap
3     Opel       2   2020     Ger
4  Ferrari       5   2025     Ita
5  Hyunday       9   2025     Kor

In [43]:
dataFrame.head(10)  # default 5 rows

      cars  counts  years origins
0      BMW       3   2024     Ger
1  Porsche       7   2026     Ger
2   Nissan       2   2023     Jap
3     Opel       2   2020     Ger
4  Ferrari       5   2025     Ita
5  Hyunday       9   2025     Kor

In [48]:
dataFrame.tail(2) # default 5 rows

      cars  counts  years origins
4  Ferrari       5   2025     Ita
5  Hyunday       9   2025     Kor

In [47]:
#shape

print('shape_of_dataFrame: ', dataFrame.shape)

shape_of_dataFrame:  (6, 4)

In [46]:
#columns

dataFrame.columns

Index(['cars', 'counts', 'years', 'origins'], dtype='object')

In [45]:
#dtypes

dataFrame.dtypes

cars       object
counts      int64
years       int64
origins    object
dtype: object

In [44]:
dataFrame.describe()   #numerical columns only

         counts        years
count  6.000000     6.000000
mean   4.666667  2023.833333
std    2.875181     2.136976
min    2.000000  2020.000000
25%    2.250000  2023.250000
50%    4.000000  2024.500000
75%    6.500000  2025.000000
max    9.000000  2026.000000

In [49]:
dataFrame.describe(include='all')   #all columns

       cars    counts        years origins
count     6  6.000000     6.000000       6
unique    6       NaN          NaN       4
top     BMW       NaN          NaN     Ger
freq      1       NaN          NaN       3
mean    NaN  4.666667  2023.833333     NaN
std     NaN  2.875181     2.136976     NaN
min     NaN  2.000000  2020.000000     NaN
25%     NaN  2.250000  2023.250000     NaN
50%     NaN  4.000000  2024.500000     NaN
75%     NaN  6.500000  2025.000000     NaN
max     NaN  9.000000  2026.000000     NaN

In [55]:
dataFrame.iloc[1] #choose only one row

cars       Porsche
counts           7
years         2026
origins        Ger
Name: 1, dtype: object

In [54]:
dataFrame.iloc[1:4] #choose from [1] to [4] => 4 is excluded

      cars  counts  years origins
1  Porsche       7   2026     Ger
2   Nissan       2   2023     Jap
3     Opel       2   2020     Ger

In [57]:
dataFrame.iloc[:4] #choose till [4] => 4 is excluded

      cars  counts  years origins
0      BMW       3   2024     Ger
1  Porsche       7   2026     Ger
2   Nissan       2   2023     Jap
3     Opel       2   2020     Ger

In [62]:
dataFrame.iloc[2:] #choose from [2]  to end

      cars  counts  years origins
2   Nissan       2   2023     Jap
3     Opel       2   2020     Ger
4  Ferrari       5   2025     Ita
5  Hyunday       9   2025     Kor

In [68]:
dataFrame.loc[1:3 , 'counts']

1    7
2    2
3    2
Name: counts, dtype: int64

In [84]:
dataFrame[dataFrame['counts'] < 5]

     cars  counts  years origins
0     BMW       3   2024     Ger
2  Nissan       2   2023     Jap
3    Opel       2   2020     Ger

In [85]:
dataFrame.mean(numeric_only=True)

counts       4.666667
years     2023.833333
dtype: float64

In [86]:
dataFrame['counts'].mean()

np.float64(4.666666666666667)

In [87]:
dataFrame.sum()

cars       BMWPorscheNissanOpelFerrariHyunday
counts                                     28
years                                   12143
origins                    GerGerJapGerItaKor
dtype: object

In [88]:
dataFrame.min()

cars        BMW
counts        2
years      2020
origins     Ger
dtype: object

In [89]:
dataFrame.max()

cars       Porsche
counts           9
years         2026
origins        Kor
dtype: object

In [90]:
dataFrame

      cars  counts  years origins
0      BMW       3   2024     Ger
1  Porsche       7   2026     Ger
2   Nissan       2   2023     Jap
3     Opel       2   2020     Ger
4  Ferrari       5   2025     Ita
5  Hyunday       9   2025     Kor

In [92]:
dataFrame.median(numeric_only=True)

counts       4.0
years     2024.5
dtype: float64

In [94]:
dataFrame.count()

cars       6
counts     6
years      6
origins    6
dtype: int64

In [95]:
dataFrame.std(numeric_only=True)

counts    2.875181
years     2.136976
dtype: float64

In [98]:
missing_data = {
    'cars' : [ None, 'Porsche', 'Nissan', None, 'Ferrari', 'Hyunday' ],
    'counts' : [ None, 7, 2, None, 5, 9 ],
    'years' : [ 2024, 2026, 2023, 2020, 2025, 2025 ],
    'origins' : [ 'Ger', None, 'Jap', None, 'Ita', 'Kor' ]
}

dataF = pd.DataFrame(missing_data)
print('dataF: ', dataF)

dataF:        cars  counts  years origins
0     None     NaN   2024     Ger
1  Porsche     7.0   2026    None
2   Nissan     2.0   2023     Jap
3     None     NaN   2020    None
4  Ferrari     5.0   2025     Ita
5  Hyunday     9.0   2025     Kor

In [100]:
dataF.isnull().sum()

cars       2
counts     2
years      0
origins    2
dtype: int64

In [102]:
dataF.dropna(how='all')

      cars  counts  years origins
0     None     NaN   2024     Ger
1  Porsche     7.0   2026    None
2   Nissan     2.0   2023     Jap
3     None     NaN   2020    None
4  Ferrari     5.0   2025     Ita
5  Hyunday     9.0   2025     Kor

In [103]:
dataF.dropna(axis=1)

   years
0   2024
1   2026
2   2023
3   2020
4   2025
5   2025

In [104]:
dataF.dropna(subset='counts')

      cars  counts  years origins
1  Porsche     7.0   2026    None
2   Nissan     2.0   2023     Jap
4  Ferrari     5.0   2025     Ita
5  Hyunday     9.0   2025     Kor

In [105]:
dataF.fillna(0)

      cars  counts  years origins
0        0     0.0   2024     Ger
1  Porsche     7.0   2026       0
2   Nissan     2.0   2023     Jap
3        0     0.0   2020       0
4  Ferrari     5.0   2025     Ita
5  Hyunday     9.0   2025     Kor

In [108]:
dataF.fillna({'cars': 'unknown', 'counts': 0, 'origins': 'unknown'})

      cars  counts  years  origins
0  unknown     0.0   2024      Ger
1  Porsche     7.0   2026  unknown
2   Nissan     2.0   2023      Jap
3  unknown     0.0   2020  unknown
4  Ferrari     5.0   2025      Ita
5  Hyunday     9.0   2025      Kor

In [112]:
Titanic_dataset = pd.read_csv('Titanic-Dataset.csv')

Titanic_dataset.head(10)

   PassengerId  Survived  Pclass  Name  Sex  Age  SibSp  Parch  Ticket  Fare
0          NaN       NaN     NaN   NaN  NaN  NaN    NaN    NaN     NaN   NaN
1          NaN       NaN     NaN   NaN  NaN  NaN    NaN    NaN     NaN   NaN
2          NaN       NaN     NaN   NaN  NaN  NaN    NaN    NaN     NaN   NaN
3          NaN       NaN     NaN   NaN  NaN  NaN    NaN    NaN     NaN   NaN
4          NaN       NaN     NaN   NaN  NaN  NaN    NaN    NaN     NaN   NaN
5          NaN       NaN     NaN   NaN  NaN  NaN    NaN    NaN     NaN   NaN
6          NaN       NaN     NaN   NaN  NaN  NaN    NaN    NaN     NaN   NaN
7          NaN       NaN     NaN   NaN  NaN  NaN    NaN    NaN     NaN   NaN
8          NaN       NaN     NaN   NaN  NaN  NaN    NaN    NaN     NaN   NaN
9          NaN       NaN     NaN   NaN  NaN  NaN    NaN    NaN     NaN   NaN

In [113]:
Titanic_dataset.to_excel('output_titanic_data.xlsx')

In [116]:
#series => 1D array

cars = pd.Series(['BMW', 'Porsche', 'Mers'])
print(cars)

0        BMW
1    Porsche
2       Mers
dtype: object

In [121]:
car_series = dataF['cars']
print(car_series)

0       None
1    Porsche
2     Nissan
3       None
4    Ferrari
5    Hyunday
Name: cars, dtype: object