<a href="https://colab.research.google.com/github/Asad3ek/ai_foundation/blob/main/Student_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd
import numpy as np

In [112]:
df = pd.read_csv("student_exam_performance.csv")
print(df)

  Student_ID  Gender  Age  Study_Hours_Per_Week  Attendance_Percentage  \
0       S001    Male   17                    12                     85
1       S002  Female   16                    15                     92
2       S003    Male   18                     8                     70
3       S004  Female   17                    20                     95
4       S005    Male   16                     5                     65
5       S006  Female   18                    14                     88
6       S007    Male   17                    10                     80
7       S008  Female   16                    18                     93
8       S009    Male   18                     7                     72
9       S010  Female   17                    16                     90

   Previous_Score Parental_Education_Level Internet_Access  \
0              68                 Bachelor             Yes
1              74                   Master             Yes
2              60              High School              No
3              88                   Master             Yes
4              55              High School              No
5              70                 Bachelor             Yes
6              65                 Bachelor             Yes
7              85                   Master             Yes
8              58              High School              No
9              78                 Bachelor             Yes

  Extracurricular_Activities  Sleep_Hours
0                        Yes            7
1                         No            8
2                        Yes            6
3                        Yes            8
4                         No            5
5                        Yes            7
6                         No            6
7                        Yes            8
8                        Yes            6
9                         No            7

In [10]:
print('dataset shape (rows, columns): ', df.shape)
print('dataset columns names: ', df.columns.tolist())

dataset shape (rows, columns):  (10, 10)
dataset columns names:  ['Student_ID', 'Gender', 'Age', 'Study_Hours_Per_Week', 'Attendance_Percentage', 'Previous_Score', 'Parental_Education_Level', 'Internet_Access', 'Extracurricular_Activities', 'Sleep_Hours']

In [12]:
print('first five rows of dataset:')
df.head()

first five rows of dataset:

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours
0,S001,Male,17,12,85,68,Bachelor,Yes,Yes,7
1,S002,Female,16,15,92,74,Master,Yes,No,8
2,S003,Male,18,8,70,60,High School,No,Yes,6
3,S004,Female,17,20,95,88,Master,Yes,Yes,8
4,S005,Male,16,5,65,55,High School,No,No,5

In [14]:
print('summary statistics: ')
df.describe()

summary statistics:

,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Sleep_Hours
count,10.000000,10.000000,10.000000,10.000000,10.000000
mean,17.000000,12.500000,83.000000,70.100000,6.800000
std,0.816497,4.949747,10.677078,11.189777,1.032796
min,16.000000,5.000000,65.000000,55.000000,5.000000
25%,16.250000,8.500000,74.000000,61.250000,6.000000
50%,17.000000,13.000000,86.500000,69.000000,7.000000
75%,17.750000,15.750000,91.500000,77.000000,7.750000
max,18.000000,20.000000,95.000000,88.000000,8.000000

In [15]:
print('data types and null info: ')
df.info()

data types and null info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  10 non-null     object
 1   Gender                      10 non-null     object
 2   Age                         10 non-null     int64
 3   Study_Hours_Per_Week        10 non-null     int64
 4   Attendance_Percentage       10 non-null     int64
 5   Previous_Score              10 non-null     int64
 6   Parental_Education_Level    10 non-null     object
 7   Internet_Access             10 non-null     object
 8   Extracurricular_Activities  10 non-null     object
 9   Sleep_Hours                 10 non-null     int64
dtypes: int64(5), object(5)
memory usage: 932.0+ bytes

In [17]:
print('Average score by columns: ')
df[['Study_Hours_Per_Week', 'Attendance_Percentage', 'Sleep_Hours']].mean()

Average score by columns:

Study_Hours_Per_Week     12.5
Attendance_Percentage    83.0
Sleep_Hours               6.8
dtype: float64

In [18]:
print('MAX score by columns: ')
df[['Study_Hours_Per_Week', 'Attendance_Percentage', 'Sleep_Hours', 'Previous_Score']].max()

MAX score by columns:

Study_Hours_Per_Week     20
Attendance_Percentage    95
Sleep_Hours               8
Previous_Score           88
dtype: int64

In [19]:
print('Min score by columns: ')
df[['Study_Hours_Per_Week', 'Attendance_Percentage', 'Sleep_Hours', 'Previous_Score']].min()

Min score by columns:

Study_Hours_Per_Week      5
Attendance_Percentage    65
Sleep_Hours               5
Previous_Score           55
dtype: int64

In [25]:
#Correlation
print(' Correlation: ')
df[['Study_Hours_Per_Week', 'Attendance_Percentage', 'Sleep_Hours', 'Previous_Score']].corr()

 Correlation:

,Study_Hours_Per_Week,Attendance_Percentage,Sleep_Hours,Previous_Score
Study_Hours_Per_Week,1.000000,0.967119,0.934606,0.988005
Attendance_Percentage,0.967119,1.000000,0.947150,0.930931
Sleep_Hours,0.934606,0.947150,1.000000,0.905675
Previous_Score,0.988005,0.930931,0.905675,1.000000

In [58]:
df['total productivity'] = df[['Study_Hours_Per_Week', 'Attendance_Percentage', 'Previous_Score']].sum(axis=1)
df['avarage productivity'] = df['total productivity'] /3
conditions = [
    df['avarage productivity'] >= 65,
    (df['avarage productivity'] >= 55) & (df['avarage productivity'] < 65)
]

choices = ['Good', 'Norm']
df['productive rate'] = np.select(conditions, choices, default='Bad')

print(df[['avarage productivity', 'productive rate']])

   avarage productivity productive rate
0             55.000000            Norm
1             60.333333            Norm
2             46.000000             Bad
3             67.666667            Good
4             41.666667             Bad
5             57.333333            Norm
6             51.666667             Bad
7             65.333333            Good
8             45.666667             Bad
9             61.333333            Norm

In [49]:
Internet_Access =df.groupby('Internet_Access')[['Study_Hours_Per_Week', 'Previous_Score']].mean()

print('student previous score by internet access: ')
print(Internet_Access)

student previous score by internet access:
                 Study_Hours_Per_Week  Previous_Score
Internet_Access
No                           6.666667       57.666667
Yes                         15.000000       75.428571

In [55]:
#avarage score of students by age
Student_Age =df.groupby('Age')[['Study_Hours_Per_Week', 'Previous_Score']].mean()

print('student previous score by Age: ')
print(Student_Age)

print('=======================================================================')

#avarage score of students by gender
Student_Gender =df.groupby('Gender')[['Study_Hours_Per_Week', 'Previous_Score']].mean()

print('student previous score by Gender: ')
print(Student_Gender)

student previous score by Age:
     Study_Hours_Per_Week  Previous_Score
Age
16              12.666667       71.333333
17              14.500000       74.750000
18               9.666667       62.666667
=======================================================================
student previous score by Gender:
        Study_Hours_Per_Week  Previous_Score
Gender
Female                  16.6            79.0
Male                     8.4            61.2

In [79]:
#check passed studends vs failed
df['total score'] = df[['Study_Hours_Per_Week','Previous_Score']].sum(axis=1)
df['avarage_score'] = df['total productivity'] /2
df['who_passed'] = np.where(df['avarage_score'] >= 65, 'Yes', 'No')
pass_rate = df['who_passed'].value_counts(normalize=True) * 100


print( pass_rate)

who_passed
Yes    90.0
No     10.0
Name: proportion, dtype: float64

In [95]:
#show all passed and failed students.

df['total_score'] = df[['Study_Hours_Per_Week','Previous_Score']].sum(axis=1)
df['avarage_score'] = df['total_score'] /2
condition =[
    df['avarage_score'] >= 50,
    df['avarage_score'] < 50
     ]
boolean = ["PASSED", "FAILED"]

df['exam_score'] = np.select(condition, boolean, default='FAILED')
print(df[['avarage_score', 'exam_score']])

   avarage_score exam_score
0           40.0     FAILED
1           44.5     FAILED
2           34.0     FAILED
3           54.0     PASSED
4           30.0     FAILED
5           42.0     FAILED
6           37.5     FAILED
7           51.5     PASSED
8           32.5     FAILED
9           47.0     FAILED

In [116]:
df['Speaking Score'] = np.random.choice([5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0], size=10)

print(df)

  Student_ID  Gender  Age  Study_Hours_Per_Week  Attendance_Percentage  \
0       S001    Male   17                    12                     85
1       S002  Female   16                    15                     92
2       S003    Male   18                     8                     70
3       S004  Female   17                    20                     95
4       S005    Male   16                     5                     65
5       S006  Female   18                    14                     88
6       S007    Male   17                    10                     80
7       S008  Female   16                    18                     93
8       S009    Male   18                     7                     72
9       S010  Female   17                    16                     90

   Previous_Score Parental_Education_Level Internet_Access  \
0              68                 Bachelor             Yes
1              74                   Master             Yes
2              60              High School              No
3              88                   Master             Yes
4              55              High School              No
5              70                 Bachelor             Yes
6              65                 Bachelor             Yes
7              85                   Master             Yes
8              58              High School              No
9              78                 Bachelor             Yes

  Extracurricular_Activities  Sleep_Hours  Listening Score  Reading Score  \
0                        Yes            7              6.5            8.0
1                         No            8              7.0            7.0
2                        Yes            6              5.0            6.5
3                        Yes            8              6.0            5.5
4                         No            5              5.5            6.5
5                        Yes            7              8.5            7.0
6                         No            6              6.0            6.5
7                        Yes            8              8.0            8.0
8                        Yes            6              6.5            8.0
9                         No            7              6.0            7.5

   Writing Score  Speaking Score
0            5.5             8.5
1            8.0             8.5
2            6.0             8.0
3            8.5             5.0
4            5.5             6.5
5            8.5             8.5
6            6.5             9.0
7            8.0             6.0
8            9.0             5.5
9            7.0             6.0

In [119]:
df[['Age', 'Listening Score', 'Reading Score', 'Writing Score', 'Speaking Score']]

   Age  Listening Score  Reading Score  Writing Score  Speaking Score
0   17              6.5            8.0            5.5             8.5
1   16              7.0            7.0            8.0             8.5
2   18              5.0            6.5            6.0             8.0
3   17              6.0            5.5            8.5             5.0
4   16              5.5            6.5            5.5             6.5
5   18              8.5            7.0            8.5             8.5
6   17              6.0            6.5            6.5             9.0
7   16              8.0            8.0            8.0             6.0
8   18              6.5            8.0            9.0             5.5
9   17              6.0            7.5            7.0             6.0

In [155]:
total_score = df[['Listening Score', 'Reading Score', 'Writing Score', 'Speaking Score']].sum(axis=1)
average_score = df['total_score'] / 4
averaged_score = df['average_score'].round(1)

print('averaged_score:\n', averaged_score)
print('---------------------------------')

#university require min score is 6.5
passed_students = df[df['averaged_score'] >= 6.5]
failed_students = df[df['averaged_score'] < 6.5]

#percentage of passed students
percentage = (df['average_score'] >= 6.5).mean() * 100

print('Students who gained enough score : ')
print(passed_students[['Student_ID', 'averaged_score']])
print('---------------------------------')
print('Students who could not gain enough score : ')
print(failed_students[['Student_ID', 'averaged_score']])

averaged_score:
 0    7.1
1    7.6
2    6.4
3    6.2
4    6.0
5    8.1
6    7.0
7    7.5
8    7.2
9    6.6
Name: average_score, dtype: float64
---------------------------------
Students who gained enough score :
  Student_ID  averaged_score
0       S001             7.1
1       S002             7.6
5       S006             8.1
6       S007             7.0
7       S008             7.5
8       S009             7.2
9       S010             6.6
---------------------------------
Students who could not gain enough score :
  Student_ID  averaged_score
2       S003             6.4
3       S004             6.2
4       S005             6.0

In [163]:
#convert scores to numpy array
scores = df[['Listening Score', 'Reading Score', 'Writing Score', 'Speaking Score']].values

print('numpy mean: ', np.mean(scores, axis=0))
print('numpy std daviation: ', np.std(scores, axis=0))

print('------------------------------------')
#z-score(normalize)
z_score = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print('z-score(normalized numbers)')
print(z_score)

numpy mean:  [6.5  7.05 7.25 7.15]
numpy std daviation:  [1.02469508 0.78898669 1.25       1.41509717]
------------------------------------
z-score(normalized numbers)
[[ 0.          1.20407608 -1.4         0.95399809]
 [ 0.48795004 -0.06337243  0.6         0.95399809]
 [-1.46385011 -0.69709668 -1.          0.60066547]
 [-0.48795004 -1.96454518  1.         -1.51933029]
 [-0.97590007 -0.69709668 -1.4        -0.45933241]
 [ 1.95180015 -0.06337243  1.          0.95399809]
 [-0.48795004 -0.69709668 -0.6         1.30733072]
 [ 1.46385011  1.20407608  0.6        -0.81266504]
 [ 0.          1.20407608  1.4        -1.16599767]
 [-0.48795004  0.57035183 -0.2        -0.81266504]]

In [188]:
#how many students scored above 7?

top_scorers = df[df['averaged_score'] >= 7 ]
print('Top Scored Students: ', len(top_scorers))
print('Top Scored Students info: ')
top_scorers[['Listening Score', 'Reading Score', 'Writing Score',
             'Speaking Score']]


#how many students failed?
failed = df[df['averaged_score'] <7]
print('Failed Students: ', len(failed))
print('Failed Students info: ')
failed[['Listening Score', 'Reading Score', 'Writing Score', 'Speaking Score']]

Top Scored Students:  6
Top Scored Students info:
Failed Students:  4
Failed Students info:

   Listening Score  Reading Score  Writing Score  Speaking Score
2              5.0            6.5            6.0             8.0
3              6.0            5.5            8.5             5.0
4              5.5            6.5            5.5             6.5
9              6.0            7.5            7.0             6.0